# -*- coding: utf-8 -*-
"""metode reiman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sG9FxVDUyXLgX3v4-XMdbCg-7D8s3Va
"""

#reiman n = 10
import numpy as np
import matplotlib.pyplot as plt
def func(x):
    return (x**2)*np.exp(-x)
# untuk n = 10 
a =1
b =10
n =10
x = np.linspace(a,b,n)
dx = (x[-1]-x[0])/(n-1)
hasil = 0
for i in range(n-1):
    hasil +=dx*func(x[i])
print(hasil)

xp = np.linspace(a,b)
plt.plot(xp,func(xp))
for i in range (n -1 ):
    plt.bar (x[i],func(x[i]),align = 'edge',width = dx, color='red', edgecolor = 'black')
plt.show()

# reiman n = 100 
import numpy as np
import matplotlib.pyplot as plt
def func(x):
    return (x**2)*np.exp(-x)
a =1
b =10
n =100
x = np.linspace(a,b,n)
dx = (x[-1]-x[0])/(n-1)
hasil = 0
for i in range(n-1):
    hasil +=dx*func(x[i])
print(hasil) 

xp = np.linspace(a,b)
plt.plot(xp,func(xp))
for i in range (n -1 ):
    plt.bar (x[i],func(x[i]),align = 'edge',width = dx, color='grey', edgecolor = 'black')
plt.show()
Footer
© 2022 GitHub, Inc.

# reiman n = 1000 
import numpy as np
import matplotlib.pyplot as plt
def func(x):
    return (x**2)*np.exp(-x)
a =1
b =10
n =1000
x = np.linspace(a,b,n)
dx = (x[-1]-x[0])/(n-1)
hasil = 0
for i in range(n-1):
    hasil +=dx*func(x[i])
print(hasil)

xp = np.linspace(a,b)
plt.plot(xp,func(xp))
for i in range (n -1 ):
    plt.bar (x[i],func(x[i]),align = 'edge',width = dx, color='yellow', edgecolor = 'black')
plt.show()